### ISSUE TITLE
Orgs list is misleading

### ISSUE THREAD

**Issue by jsumners** [No9/project-stats#1]
When you run this app for `fastify/fastify` you'll get orgs from my profile that really have no influence. I'm not sure how you can filter such orgs, but maybe by a member count? For example, if an org in a contributor's list has a single member then it probably isn't a real "organization" that influences anything.

**Comment by No9** [comment]
Hey @jsumners Thanks for the comment 
The idea of the "Influencing Organisations" was to capture when multiple contributors from a single organisation are contributing but also highlight that different orgs are contributing.
The latter requirement means that capturing the tail or single orgs is necessary. 
Admittedly this looks noisy in the fastify example but it is useful in certain scenarios. 
That said your point is valid.
Maybe a title change to "Possible Influencing Organisations" would cover it but I am open to other suggestions.

**Comment by jsumners** [comment]
I can say for certainty that the PL/JSON and AtlSynth (Atlanta Synthesizer Club) will never be an influence to Fastify. I completely agree that the Knockaway org could be an influence. Hence my suggestion of checking the orgs for member numbers if possible. 

A compromise might be to list the influencing members and orgs in a table. Member is first column and second column is the orgs they are attached to.

**Comment by No9** [comment]
Thanks for clarifying some more. It seems like the underlying problem is the term "influencing"
"Influencing" draws an incorrect inference on the relationship between the other organisations of a collaborator and the target project.
I think changing the name to the more direct "Contributors Aggregated by Organizations"  is the better option and leave the conclusion around influence to the viewer.
I'm not sure listing the members related orgs is the right option in this case as it would hide some key information.

**Comment by No9** [comment]
I've removed the term influence from the project in this PR https://github.com/No9/project-stats/commit/91c13c74d1f8bf755c144caaa43ffeb7077fefe1

**Comment by jsumners** [comment]
There's still no context that explains how the information is relevant. Sticking with my specific case, what does `pljson` showing up "contributors aggregated by organizations" mean? Does that mean the PL/JSON org contributed to the `fastify/fastify` project? _I_ know it didn't because it's brought in through my orgs, but what about Jane Smith who is viewing this as a completely uninformed party?

**Comment by No9** [comment]
Hey again 
"contributors aggregated by organizations" is just a description of the data.
In the specific case it identifies that 1 of the contributors is also associated with `pljson`.

What that *means* and it's relevance is dependent on the reader and the organisations identified. 
But with the previous title Jane Smith would have been led to believe that `pljson` influenced fastify. 
Now she is just presented with the other organisations the contributors are related too. 
She may be involved with those other organisations or have previous experience of those orgs but that is beyond the scope of this project. 

Maybe `Other Organisations the Contributors are Related To` is an improvement on the title? 
But anything more risks giving false interpretations again.

**Comment by jsumners** [comment]
I think the `icon + number` is what really makes it difficult for me. It's like a third of the information is missing that would make the section useful. I think one of the two tables below would solve it for me. My intention with this issue was merely to try and get the information to be relevant and make sense given that I know I'm not the only contributor that creates orgs for literal project organization and not to represent a third party entity.

| Contributor | Orgs |
| ---         | ---  |
| jsumners    | [fastify icon], [pljson icon], etc |

| Org         | Contributor |
| ---         | ---  |
| [fastify icon]    | jsumners, someone_else, another_person |
| [pljson icon] | jsumners |

**Comment by No9** [comment]
Ah! That's super useful - I knew I was missing something in your explanation just couldn't for the life of me work it out. 
I'd also like to keep the count so will add a total column 
| Contributor | Orgs |Total|
| ---         | ---  |---  |
| jsumners    | [fastify icon], [pljson icon], etc |2|

| Org         | Contributor |Total|
| ---         | ---  |---  |
| [fastify icon]    | jsumners, someone_else, another_person |3|
| [pljson icon] | jsumners |1|

Going to start iterating on this.

**Comment by jsumners** [comment]
Excellent.

**Comment by No9** [comment]
OK I've deployed a version of this at https://project-stats.netlify.app/ 
Page feels a little long now but I'm going to leave it as it is unless other features start to be requested.

**Comment by jsumners** [comment]
Looks good to me. I was really suggestion one or the other of the tables, dealer's choice. But both is cool too.

I don't know what happened, here, but it was a fun surprise 🤣 

![image](https://user-images.githubusercontent.com/321201/144955122-0f2b595c-bc17-40c0-a1b7-b90b6912b43a.png)

**Comment by No9** [comment]
Thanks for your patience getting the requirement across. We got there in the end.
I'm using the direct call to the image endpoint for the avatars 
https://github.com/${data[s].userid}.png?size=32 
and it looks like the size parameter isn't being respected when it's an GH generated avatar :( 
I've updated the page to force the image size with an inline style.
